# Home Work_1

### a_tensor_initialization

In [7]:
import torch
# torch.Tensor class
"""Tensor() : 자료형 1,2,3을 float32형태인 1.0, 2.0, 3.0 형태로 변환해며, device는 cpu로 연산"""
t1 = torch.Tensor([1, 2, 3], device='cpu')

print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()   #t1의 텐서를 cpu로 기동

print("#" * 50, 1)

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1


 PyTorch에서 기본적인 텐서 클래스입니다. torch.Tensor는 기본적으로 torch.float32 자료형의 텐서를 생성하는 것을 배웠으며 관련한 메서드까지 이해할 수 있게 되었다.<br><br>
 그에 관련한 메서드<br>
 dtype : t1의 데이터 타입<br>
 decive : 현재 사용되는 연산장치 (GPU와 CPU)<br>
 requires_grad : 자동 미분엔진으로 gridiant(기울기)값을 계산하기 위한 메서드, 신경망 학습에 필요하며 역전파 알고리즘에 사용된다.<br>
 size()와 shape : 모두 텐서의 크기를 출력한다. 차이점은 size()는 메서드로 호출하며 shape는 속성으로 바로 접근이 가능하다.

In [8]:


# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])
# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu() #tensor를 cpu로 기동

print("#" * 50, 2)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2


t1과 다르게 Tensor()이 아닌 tensor()을 사용했으며 Tensor()은 float64의 형태이지만 tensor()은 int64의 형태이다.

In [9]:
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])
print(a11.shape, a11.ndim)

""" 수정된 코드
a11 = torch.tensor([                 
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
])
print(a11.shape, a11.ndim)

또는

a11 = torch.tensor([                 
    [[[1, 2], [4, 5]]],
    [[[1, 2], [4, 5]]],
    [[[1, 2], [4, 5]]],
    [[[1, 2], [4, 5]]],
])
print(a11.shape, a11.ndim)
"""

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

가장 복잡해 보이는 a9를 가지고 이해를 하자면<br>
shape: [3, 1, 2, 3, 1]: 5차원 텐서이며, 각 차원은 차례로 크기가 [3, 1, 2, 3, 1]이다.<br>
첫 번째 차원: 리스트 3개<br>
두 번째 차원: 각 리스트에 1개의 하위 리스트<br>
세 번째 차원: 각 하위 리스트에 2개의 하위 리스트<br>
네 번째 차원: 각 하위 리스트에 3개의 요소<br>
다섯 번째 차원: 각 요소가 [ ]로 감싸진 상태 (크기 1)
결론 적으로 shape는 각 차원에 대한 크기에 대해서 나타난 것이다.<br>
ndim : 차원의 개수를 나타낸 것<br><br>
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ<br>
a11의 에러의 사유는 [[1, 2, 3], [4, 5]] 첫 번째 리스트와 두 번째 리스트의 차원의 개수가 맞지 않기 때문이다.<br>
해결 방법은 [[1, 2, 3], [4, 5, 6]]하거나 [[1, 2], [4, 5]] 이런 식으로 원소의 개수를 맞춰주어야 한다.

### b_tensor_initialization

In [10]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)    # 리스트를 가지고 했으므로 메모리 참조를 하지 않는다.

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

print("#" * 100)

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)    # Numpy리스트를 가지고할 때 Numpy와 메모리를 공유하는 방식

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


Tensor() : 자료형이 float64형태이므로 소수점이 붙게된다.<br>
tensor() : 자료형이 int64인 형태<br>
as_tensor() : 메모리를 공유하는 형태로 일반적인 tensor는 복사하여 가져오지만 Numpy와 같이 사용할 경우 메모리를 참조하여 값을 가져오게 된다.

### c_tensor_initialization

In [2]:
import torch

t1 = torch.ones(size=(5,))  # or torch.ones(5)
t1_like = torch.ones_like(input=t1)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

t4 = torch.eye(n=3)
print(t4)

# 추가 코드 - 1로 초기화된 텐서를 가지고 zeros_like에 인풋값으로 넣게 되면 어떤식으로 되는 지 궁금하여 진행
t5 = torch.ones(size=(5,))  
t5_like = torch.zeros_like(input=t5)
print(t5)  
print(t5_like)  


tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0.0000e+00,        nan, 0.0000e+00, 1.0688e-05])
tensor([0.0000, 1.8750, 0.0000, 0.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0.])


ones(size=(n,)) : 크기가 n인 텐서를 생성하고, 값은 모두 1로 초기화<br>
ones_like(input) : 입력 텐서와 동일한 크기의 텐서를 1로 초기화하여 생성<br>
zeros(size=(n,)) : 크기가 n인 텐서를 생성하고, 값은 모두 0으로 초기화<br>
zeros_like(input) : 입력 텐서와 동일한 크기의 텐서를 1로 초기화<br>
empty(size=(n,)): 크기가 n인 텐서를 생성하지만, 값은 초기화되지 않음<br>
empty_like(input): 입력 텐서와 동일한 크기의 초기화되지 않은 텐서 생성<br>
eye(n): n x n 크기의 단위 행렬을 생성

### d_tensor_initialization

In [3]:
import torch

t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

t2 = torch.rand(size=(1, 3))
print(t2)

t3 = torch.randn(size=(1, 3))
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

t6 = torch.arange(5)
print(t6)

print("#" * 30)

torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[14, 10]])
tensor([[0.9554, 0.5719, 0.2492]])
tensor([[-2.1408,  0.4415,  0.2381]])
tensor([[ 8.2957,  8.6132],
        [ 9.2476, 10.4913],
        [11.1628,  9.4551]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


randint(low, high, size) : low부터 high(exclusive)까지의 범위에서 정수 난수를 생성<br>
rand(size) : [0.0, 1.0) 범위 내에서 균등 분포를 따르는 난수로 채워진 텐서를 생성<br>
randn(size) : 평균이 0이고 표준 편차가 1인 정규 분포(가우시안 분포)를 따르는 난수로 텐서를 생성<br>
normal(mean, std, size) : 평균이 mean 표준 편차가 std인 정규 분포를 따르는 난수를 생성<br>
linspace(start, end, steps) : start에서 end까지를 steps=3개의 균등한 간격으로 나눈 값을 가지는 텐서를 생성<br>
arange(end) : 0부터 end까지의 범위에서 1씩 증가하는 값을 가지는 텐서를 생성<br>
manual_seed(seed) : 난수 생성기의 시드를 설정하여, 동일한 시드값을 사용하면 동일한 난수를 생성<br>

### e_tensor_type_conversion

In [5]:
import torch

a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 2.6417, 10.9639, 12.7832],
        [ 2.9583,  8.8599, 17.0116]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


ones(): 주어진 크기와 데이터 유형으로 모든 요소가 1인 텐서 생성<br>
dtype: 텐서의 데이터 타입을 지정하거나 조회<br>
rand(): [0.0, 1.0) 범위에서 랜덤한 값으로 채워진 텐서 생성<br>
to(): 텐서의 데이터 유형을 변환하거나 장치 변경<br>
tensor(): 입력값을 텐서로 변환하고 원하는 데이터 유형 지정<br>
double(): 텐서를 torch.double(float64) 데이터 타입으로 변환<br>
short(): 텐서를 torch.short(int16) 데이터 타입으로 변환<br>
type(): 텐서의 데이터 유형을 명시적으로 변환

### f_tensor_operations

In [4]:
import torch

t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

print("#" * 30)

t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


ones(): 주어진 크기와 데이터 유형으로 모든 요소가 1인 텐서 생성<br>
add(): 두 텐서를 요소별로 더한 결과 생성<br>
+: 두 텐서를 요소별로 더한 결과 생성<br>
sub(): 두 텐서를 요소별로 뺀 결과 생성<br>
-: 두 텐서를 요소별로 뺀 결과 생성<br>
mul(): 두 텐서를 요소별로 곱한 결과 생성<br>
*: 두 텐서를 요소별로 곱한 결과 생성<br>
div(): 두 텐서를 요소별로 나눈 결과 생성<br>
/: 두 텐서를 요소별로 나눈 결과 생성<br>

### g_tensor_operations_mm

In [3]:
import torch

t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())

tensor(7) torch.Size([])
tensor([[-1.7824, -0.3100],
        [-1.2367, -3.3209]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


dot(): 두 1D 텐서의 내적(스칼라 곱) 계산<br>
size(): 텐서의 크기 반환<br>
randn(): 평균 0, 표준편차 1을 따르는 정규분포(가우시안 분포)에서 랜덤한 값으로 텐서 생성<br>
mm(): 두 2D 텐서 간의 행렬 곱 계산<br>
bmm(): 배치 단위로 3D 텐서 간의 행렬 곱 계산<br>

### h_tensor_operations_matmul

In [2]:
import torch

# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])


torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


matmul(): 벡터, 행렬, 배치 행렬 간의 곱셈을 처리하며, 입력 차원에 따라 적절한 행렬 곱 계산<br>
size(): 텐서의 크기 반환<br>
randn(): 평균 0, 표준편차 1을 따르는 정규분포에서 랜덤한 값으로 텐서 생성



### i_tensor_broadcasting

In [1]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)


def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

tensor(): 주어진 값으로 텐서를 생성<br>
*: 요소별 곱셈 연산<br>
-: 브로드캐스팅을 통해 두 텐서의 요소별 뺄셈 연산<br>
+: 브로드캐스팅을 통해 두 텐서의 요소별 덧셈 연산<br>
add(): 요소별 덧셈 연산<br>
sub(): 요소별 뺄셈 연산<br>
mul(): 요소별 곱셈 연산<br>
div(): 요소별 나눗셈 연산<br>
randn(): 평균이 0이고 표준 편차가 1인 정규 분포에서 난수 생성<br>
normalize(): 입력 텐서를 255로 나눠 정규화하는 함수 정의<br>
empty(): 주어진 크기로 초기화되지 않은 텐서 생성<br>
pow(): 텐서의 각 요소에 대해 거듭제곱 연산<br>
arange(): 주어진 범위에서 일정한 간격으로 값이 증가하는 텐서 생성<br>
브로드캐스팅: 텐서 간 차원이 맞지 않을 때 자동으로 일치시켜 연산을 수행하는 방식<br>

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ<br>
브로드캐스팅 규칙 <br>
- 작은 크기의 텐서가 큰 텐서의 크기와 일치할 때까지 자동으로 확장<br>
- 크기가 1인 차원은 다른 텐서의 해당 차원 크기로 확장 가능

### j_tensor_indexing_slicing

In [6]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)


tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


- **`tensor()`**: 주어진 값으로 텐서를 생성
- **`[]`**: 인덱싱 및 슬라이싱을 사용하여 텐서의 특정 값 또는 부분을 선택
    - **`x[1]`**: 1번째 행 선택
    - **`x[:, 1]`**: 모든 행에서 1번째 열 선택
    - **`x[1, 2]`**: 1번째 행의 2번째 열 값 선택
    - **`x[:, -1]`**: 모든 행에서 마지막 열 선택
- **슬라이싱**: 텐서의 일부분을 선택하는 연산
    - **`x[1:]`**: 1번째 행부터 끝까지 선택
    - **`x[1:, 3:]`**: 1번째 행부터 끝까지, 3번째 열부터 끝까지 선택
- **`zeros()`**: 주어진 크기만큼 0으로 채워진 텐서를 생성
    - **`y[1:4, 2] = 1`**: 1부터 3번째 행의 2번째 열에 값을 1로 할당
    - **`y[1:4, 1:4]`**: 1~3번째 행과 1~3번째 열의 서브 텐서 선택
- **텐서 변경**: 특정 부분에 값을 할당하여 텐서의 값을 변경
    - **`z[1:, 1:3] = 0`**: 1번째 행부터 끝까지, 1~2번째 열에 값을 0으로 변경

### k_tensor_reshaping

In [8]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

print("#" * 50, 2)

# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

print("#" * 50, 4)

t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


tensor(): 주어진 값으로 텐서를 생성<br>
view(): 텐서의 크기를 변경하되, 텐서의 데이터는 유지하면서 새 모양을 반환<br>
reshape(): 텐서의 크기를 변경하는 또 다른 방법으로, 필요시 데이터를 재배치하여 새 모양을 반환<br>
arange(): 주어진 범위 내에서 일정한 간격으로 값이 증가하는 텐서 생성<br>
squeeze(): 차원이 1인 모든 축을 제거하거나, 특정 축의 차원이 1일 경우 제거<br>
unsqueeze(): 주어진 위치에 새로운 차원을 추가<br>
flatten(): 다차원 텐서를 1차원으로 변환<br>
permute(): 주어진 순서대로 텐서의 차원을 재배치<br>
transpose(): 두 차원을 교환하여 텐서의 차원을 변경<br>
t(): 2차원 텐서의 전치를 계산하는 메서드

### L_tensor_concat

In [10]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape) # t1, t2, t3를 dim=1에서 병합하면 결과 텐서의 크기는 [2, 6, 3]이 됨

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])


torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

zeros(): 주어진 크기만큼 0으로 채워진 텐서를 생성<br>
arange(): 주어진 범위에서 일정한 간격으로 값이 증가하는 텐서를 생성<br>
reshape(): 텐서의 크기를 원하는 형태로 변경<br>
cat(): 여러 텐서를 주어진 차원(dim)을 따라 연결<br>

### m_tensor_stacking

In [11]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


tensor(): 주어진 값으로 텐서를 생성<br>
stack(): 주어진 차원(dim)에서 텐서를 새로운 차원으로 쌓아서 병합<br>
cat(): 주어진 차원(dim)에서 텐서를 연결(병합)하지만 차원을 추가하지 않음<br>
unsqueeze(): 주어진 위치에 새로운 차원을 추가<br>
equal(): 두 텐서가 동일한지 비교하여 True 또는 False 반환<br>
arange(): 주어진 범위에서 일정한 간격으로 값이 증가하는 텐서를 생성

### n_tensor_vstack_hstack

In [12]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


tensor(): 주어진 값으로 텐서를 생성<br>
vstack(): 주어진 텐서들을 수직으로(첫 번째 차원 기준으로) 쌓음<br>
hstack(): 주어진 텐서들을 수평으로(두 번째 차원 기준으로) 쌓음<br>
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ<br>
이해를 위한 각 출력 설명:
- **`vstack()`**: 주어진 텐서들을 첫 번째 차원(수직) 기준으로 쌓습니다.

  - `t1`과 `t2`를 수직으로 쌓아 `t3` 생성, 결과는 `[2, 3]` 크기
  - `t4`와 `t5`를 수직으로 쌓아 `t6` 생성, 결과는 `[6, 1]` 크기
  - `t7`과 `t8`을 수직으로 쌓아 `t9` 생성, 결과는 `[4, 2, 3]` 크기

- **`hstack()`**: 주어진 텐서들을 두 번째 차원(수평) 기준으로 쌓습니다.

- `t10`과 `t11`을 수평으로 쌓아 `t12` 생성, 결과는 `[6]` 크기
- `t13`과 `t14`를 수평으로 쌓아 `t15` 생성, 결과는 `[3, 2]` 크기
- `t16`과 `t17`을 수평으로 쌓아 `t18` 생성, 결과는 `[2, 4, 3]` 크기